---
slug: "1-good-to-review-after-the-lapse"
date: "2020-10-23T14:26:07+00:00"
lastmod: "2020-10-23T14:26:07+00:00"
title: "#1: 復習は忘れる前か後か"
type: "blog"
categories: ["暗記"]
tags: ["復習","忘却","単語帳","レミネセンス"]
excerpt: "学んだ内容をいつでも思い出せるようになるには、忘れる前に復習すべきなのだろうか。"
---
= タイトル
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: 学んだ内容をいつでも思い出せるようになるには、忘れる前に復習すべきなのだろうか。
:toc: macro
:toc-placement:
:toclevels: 1

{description}

toc::[]

高二の時、学校で一括購入した単語帳の定期テストがあった。定期テストの2週間前から出題範囲を覚えようとしたが、ぜんぜん覚えられず、ひどい結果だった。
カードを作って見たり、音読して見たり、紙に書き写して見ても全く覚えられなかった。
復習のタイミングも雑誌記事をたよりに今でいうSpaced Repetitionも試してみたが何の効果もなかった。
自分はなんですぐ忘れてしまうだろうと絶望した。さらに、大学入試までにこの単語帳をほとんど覚えることができなかった。

理系の学部に進学し大学受験を超える高度な英語を触れる機会もなかった。しかし、大学を卒業してこの単語帳を読み返して見たら、ほとんどの単語を覚えていることに気がついた。

これが、忘れることと覚えることの関係について興味を持ったきっかけだ。

== 忘れる前に復習する

エビングハウスの実験結果はどうだったかは置いておいて、エビングハウスの名前を持ち出している学習方法、学習アプリは、復習する前に復習すれば、記憶は効率的に強化されるという考え方を採っている。その復習するタイミングを管理する手法として Spaced Repetition がよく使われている。link:https://www.supermemo.com/en/archives1990-2015/english/ol/sm2[Supermemoのアルゴリズム SM2] が特に有名だ。

一度覚えた情報を復習する時、復習間隔を一定の定数倍で広げていくと、記憶保持の効率が高くなるという考え方で、SM2 アルゴリズムではEFは初期値は 2倍(ただし5回目以降の復習)で、覚えにくい情報はこの定数を減らしていくと、それぞれの難易度に見合った最適な数が決まる。この定数のことを EF(Ease Factor)と呼ぶ。

//つまり、この方法はそれぞれの暗記項目を忘れる前に復習するようにEFを管理していくやり方だ。

このやり方は、全ての暗記項目を忘れないように復習する。
そして最も効率的な復習タイミングをEFによって調節している。

これは、紙で可能だし、対応アプリは多数ある。

////
ちなみに、実際の観察結果によれば、 Ease Factor は1.4から3の間で機能するそうだ。1.4以下だと Spaced Repetition の効果が得られないし、3以上だとほどんど覚えていられなくて失敗するらしい。

高校時代、Spaced Repetitionを使おうとした時はEFを3にしていた。だから、Spaced Repetitionのアルゴリズムを学び始めた時には、EFの値が大き過ぎたのが高校時代の失敗したのでと理解した。
////

そして、link:https://apps.ankiweb.net/[Anki] を使うことで、link:http://testyourvocab.com[testyourvocab.com]で20,000語レベルまで語彙数を伸ばすことができた。

これだけの効果を目の当たりにして、高校時代の失敗は復習のタイミングを管理できなかったのが原因なのだろうと納得した。。

== 忘れた後に復習する

踊りを学ぶようになって、レッスン当日には全くできなかったジャンプのテクニックや振り付けが、後日のレッスンでいとも簡単にできてしまう経験を度々した。そこでネットで調べて見たところ、レミネセンス効果のバラード・ウィリアムズ現象 (Ballard-Williams reminiscence phenomenon) として心理学の世界で知られているとわかった。

この現象を有効活用した学習法は、ゴールドリスト法 (Goldlist method) だろう。ゴールドリスト法の注意点はバラード・ウィリアムズ現象を活用した学習法そのものだ。

この方法は復習までに積極的に忘れようとしている。その点が直前に話したSpaced Repetitionとの決定的な違いだ。そして直感や常識に反することだ。ゴールドリスト法を挫折するした人の言い分は、忘れている項目が過ぎて効率的ではないということだ。

一旦忘れた学習内容を再度学び直すことの意義を理解しないと、継続することは難しいと思う。

== 驚きの体験を再度振り返る

最初の高二の頃の単語帳の定期テストのエピソードに戻る。定期試験では全くできず、大学受験に間に合ったかは疑わしいが、最終的に全ての単語を覚えてしまった。よくよく当時を振り返ってみると、忘れる前に復習したわけではない。数ヶ月おきに目的もなく単語帳を眺めて、その度に忘れていることに絶望していただけだ。しかし、最終的には覚えてしまったのだ。


十分忘れた頃に読み返していたら、記憶してしまったのが真相だ。この方法は試験のような数ヶ月後の期日ではうまく機能しないが、年単位の長期的な計画ならかなり有望だ。

記憶のために一旦すっかり忘れる効用について述べた研究はほとんど見たことがない。

直感に反することなので、広く受け入れられないことなのだと思うが、意識的にこの手法を使って、実際の効果を評価していこうと思う。

また、どこかにいる高二の自分のために、定期テストのための単語帳の覚え方は後日説明しようと思う。

== 参考情報

.紙を使ったSpaced Repetitionの実例

* link:https://www.supermemo.com/en/archives1990-2015/articles/paper[Using SuperMemo without a computer]

* link:https://rs.luminousspice.com/pen-and-paper-anki/[紙とペンで簡単にできる Anki]


