---
slug: "2-revert-back-to-the-original"
date: "2020-10-24T03:24:24+00:00"
lastmod: "2020-10-24T03:24:24+00:00"
title: "#2: 訳文を原文に戻す練習"
type: "blog"
categories: ["作文"]
tags: ["復文","翻訳"]
excerpt: "訳文を原文に戻す練習を始めてみた"
---
= タイトル
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: 訳文を原文に戻す練習を始めてみた
:toc: macro
:toc-placement:
:toclevels: 1

{description}

toc::[]

言語の練習の中に、翻訳した文章を再び元の言語に翻訳し戻す方法がある。これは統語法を学ぶのに良い方法だそうだ。

== 原文に戻す学び方にはいろいろな呼び方がある

例えば、漢文の書き下し文を白文に戻すことはかつて広く行われていて、戦前の官立学校では入学試験に出題していたらしい。この場合は「復文」と呼ぶことが多い。また、英文解釈や英作文の先生の中には一旦和訳したものを英語に戻すことを「反訳」と表現することもある。

また、英語学習法の情報の中には「原文復元法」と呼ぶこともある。これは渡部昇一「[link:https://www.amazon.co.jp/dp/4061455389[続 知的生活の方法]」に一生設けて詳しく説明している学習方法だ。ベンジャミンフランクリンの自伝に説明している文章練習方法を、英文執筆の練習法に渡部氏自身がアレンジしたものだ。この方法については、link:https://tokyo-metro-u.repo.nii.ac.jp/?action=repository_action_common_download&item_id=6624&item_no=1&attribute_id=18&file_no=1[都立大学の英作文の授業では実地例の報告]がある。

== 復文用の教材探し

この復文学習法に興味を抱きつつ、いつも二の足を踏んでいたのは、良い教材が見つからなかったからだ。最初は山岡洋一のlink:http://www.honyaku-tsushin.net/ron/bn/kogui0801.html[翻訳通信の記事]を参考にして、名翻訳と原文で挑戦しようとしたが、分量が多すぎてとても最後まで続ける自信がなかった。他に英語の参考書を探してみたが、原文と訳文が近くにありすぎて、使い勝手が良くない。

たまたま、英文読解用の例文集を開いたら、とても復文に都合の良い構成だった。この例文集は、2-3の例文をあげ、読み方の解説が続く。さらに、2-3文程度で書かれた練習問題で練習するという構成だ。都合の良いことに、練習問題の解答は巻末にまとめられている。600題くらいの復文用練習集になる。

最初から原書を取り組むと、負担が高く効果が体感できる前に挫折しそうなので、まずはゆるい方法で試すことにした。

== 復文を練習して気がついたこと

復文学習方法では、まず和訳の作業があり、その後原文に戻す。復文で学ぶ目的は、対象言語の表現力向上であるし、なるべく負担を減らして継続したかったので、和訳の作業は省略した。

実際に解いてみると、どんどん自由作文のように英文を書いていったのだが、和訳から透けて見える基本例文とその文法事項に気がついた。このまま、自分の使う表現で簡潔に書きつづけるか、元の例文に従って書き戻すか迷った。まず自分の書きたいように書いて、基本例文に沿った文も追加するようにした。

そうすると、本文中で説明している文法事項が頭に残るようになり、とても調子がいい。コロケーションの理解を深めるために始めたのだが思わぬ副産物だ。

== 今後の予定

今のペースで行くとこの例文集は3ヶ月で終了できる予定だ。その後のアイデアをまとめておく。

文語文、つまり古文の復文ができないかと考えている。かつては日本人は文語文が自然にかけたが、いまでは現代文あるいは口語文しか書けなくなってしまった。文語文を書くための練習書はいくつかあるが、復文を使って見たら、より効果的で楽しくできるのではと思っている。

英語については、高校の頃使っていた対訳本、そして前に挙げた翻訳通信で紹介している名訳本を使ってみたいと思う。