---
slug: "how-to-learn-vocabulary-book-for-exam"
date: "2020-10-30T13:38:48+00:00"
lastmod: "2020-10-30T13:38:48+00:"
title: "#4: 定期試験のための単語帳の覚え方"
type: "blog"
categories: ["暗記"]
tags: ["単語帳","英単語"]
excerpt: "どこかにいるはずの高校2年生の自分に向けて学校の定期試験に向けての単語帳の勉強の仕方を説明するよ"
---
= 定期試験のための単語帳の覚え方
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: どこかにいるはずの高校2年生の自分に向けて学校の定期試験に向けての単語帳の勉強の仕方を説明するよ
:toc: macro
:toc-placement:
:toclevels: 1
:icons: font

{description}

toc::[]


十分忘れてから復習することの意義についてlink:/blog/1-good-to-review-after-the-lapse/[以前の記事]で説明した。高校生の頃この体験がないために、学校の定期テストでとても苦しんだ。どこかにいるはずの高二の自分に単語帳の使い方を説明する。

== 最初にわかってほしいこと

単語を覚えるまでに、3つの段階がある。

. 見たこともない単語
. 忘れた単語
. 覚えた単語

新しく出会った単語は記憶するまでに一旦忘れる段階を通る。だから、覚えようとした単語を忘れるというのは、一歩前進している。忘れたというのは積極的な意味を持っている。

確かに、一部の単語は見てすぐに完璧に覚えたしまうが、全ての単語がその場で覚え切らなくても絶望することはない。忘れることは記憶するためのとても大切だ。そして、見たこともない単語を継続して減らしていけば、最終的にはほぼ全ての単語を暗記できる。

すぐに覚えられないからといって、直ぐガッカリして諦めないでほしい。

== 定期テストのむけの準備の仕方

高二の頃使った単語帳は見出し語が1,400あり、10回の定期テストで、140語ずつ出題された。
単語帳は見開き2ページで10語を学ぶ。左ページは見出し語と語義、右ページは見出し語を使った、英文和訳と和文英訳の空欄補充問題だ。
定期試験はいつも2週間前から準備していたので、2週間でテスト範囲の140語を覚える方法を説明する。

=== テスト範囲を覚えるスケジュール

準備期間の20％を新しい単語を学ぶ期間にあて、残りの80%を復習に使う。つまり、2週間の準備期間なら、3日間でテスト範囲のページを全て目を通す。残りの11日はひたすら復習すればよい。

=== 初めて見るページの学び方

一日10ページずつテスト範囲を通読する。左ページ一行ずつ横に読んでいく。そして右ページに移り穴埋め問題を見て思い出せるか確かめる。大体20分もあれば通読できる。決して無理に暗記しようとしてはいけない。余力があれば繰り返してもいい。3日かけて試験範囲を全て読み通す。

=== 復習の仕方

4日目からは復習セッションを始める。

. 左ページの見出し語を縦に順番に見て、意味が思い出せるかチェックしていく。一つでも意味が思い出せれば、その単語の左に / スラッシュを書き込む。
. 右ページの穴埋め問題を見て、思い出せるかチェック。わかった問題はスラッシュを入れる。
. 見開き2ページが終わったらページをめくって、次のページを復習する。知っている単語や問題には目印を入れる。試験範囲の最後まで続ける。

. 最後まできたらまた最初からチェックする。太字で書かれた重要な語義が思い出せれば、逆方向のスラッシュ　\ を入れる。以前の復習でわかっていた単語は　X が前に入ることになる。右ページは、すでにスラッシュ / が前についている問題は飛ばして、知らない問題だけをやる。そして、テスト範囲の最後まで続ける。

. また初めから復習し直す。見出し語が X が付いている単語は飛ばす。/ がついている空欄補充問題も飛ばす。わかっている問題はどんどん目印をつける。

. もし最初から20分以上経っていなければ、さらに繰り返しても良い。ここでやめても良い。

このような復習セッションを毎日繰り返す。

=== 役立つ体験談

最近見たYouTubeの動画の中で、同じような方法を紹介している動画見つけた。この動画の中でりゅうさんがシステム英単語を200周した方法とその効果を紹介している。
 
{{< ytmodal uKqAH5rOap0 >}}

テスト範囲は28ページだけなので、もっと楽にできるはずだ。りゅうさんは例文を音読したそうだが、まえに説明したように音読を繰り返すよりも、音読を録音して再生速度を上げて繰り返し聞くことを勧める。

== 練習時間について

1日あたり1時間以上このような単語の勉強をしてはいけない。できれば、1日の中でも分割して練習すると良い。例えば朝、昼、晩に3分割して10分ずつでも良い。一度に集中して何回も繰り返すよりも、時間をおいて前の練習の記憶が消えた後にやると良い。

== おすすめの技術

定期テストでの単語帳学習で重要な技術をまとめておいた。

* スピード感が重要

テンポよくどんどん単語を見ていく。自分の限界の挑戦するつもりで。

* 優先順位を厳守

知っている単語に時間は使わない。マークのついていない忘れた単語だけに時間を使う。
 
* 録音で復習

わからない単語だけ、スマホに吹き込んで復習すると効果的。再生する場合は2倍速までなら聞き取り可能。何回でも高速に反復できるのでオススメ。

* 視聴覚のバランス

見る:聞く:言う:書く=100:30:10:1 くらいのバランスが良い。書くのはスペルを覚えることにしか役立たない。定期試験で使えるのは単語を見たら瞬時に意味が思い出せる状態なので、見て覚えることを中心に練習していくと良い。

声に出してもいいが、繰り返すのは疲れるし、喉が痛くなる。そこでスマホに録音し、聞いて覚えることは、どこでも気軽にできるの勧めたい。自分の声を聞くのは初めは嫌悪感を感じるがなれると頭に残りやすい。

== 定期試験3日前からの最後の詰め

3日前になったら、試験範囲の中で自分が重要だと思う単語を使った予想問題を使って解いておく。これは純粋に書く練習をするためだ。綴りがややこしい問題、日本語訳の漢字が書きにくい問題に対応すると役立つ。


== 定期試験が終わったら

そのまま、単語を覚え続けて、1ヶ月以内に単語帳丸ごと一冊覚えてしまうこと。この単語帳は5,000レベルの単語が学べるので、これで大学入試で必要な単語は完成だ。
この単語帳をマスターすれば、読解や、文法、作文でよりレベルの高い練習ができるようになる。
あとは、今やっている通り教科書や問題集で出会った知らない単語を拾って覚えていけば良いよ。

{{< ytmodal-script >}}
