---
slug: "5-how-to-learn-pattern-sentences"
date: "2020-10-31T01:52:47+0000"
lastmod: "2020-10-31T01:52:47+00:00"
title: "#5: 文法書の例文を覚えることとは"
type: "blog"
categories: ["暗記"]
tags: ["例文","構文","読解","文法"]
excerpt: "文法書の例文を覚えることの効用について考えをまとめた"
---
= 文法書の例文を覚えることとは
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: 文法書の例文を覚えることの効用について考えをまとめた
:toc: macro
:toc-placement:
:toclevels: 1
:icons: font

{description}

toc::[]


== 例文集を覚えようとしたが

link:/blog/2-revert-back-to-the-original/[復文の練習に例文集を使っていること]について以前話したが、その例文集に出会った経緯を書く。

高一の時の英語の先生がとても素晴らしかった。外大の英米語専攻した先生で、新卒ですぐ本採用になったぐらいなので相当優秀だと思うのだが、残念ながら当時はその良さが全く理解できなかった。大学以降英語を学び直した時、この先生が勧める方法を結果としてなぞることになった。高校生の頃素直にこの先生のいうことを言いていればよかったと思う。

おそらく、高校入学当初にどの単語帳を学ぶべきか質問したのだと思うのだが、まず熟語集を暗記すること、つぎに学校指定の文法の参考書の例文を暗記することを勧められた。これは、先生が入試の頃使っていた教材だそうだ。文法を説明する例文を暗記する意義が理解できず、他になにか良い本がないかと質問したところ勧めてくれたのが、同じ著者の英文読解のための例文集だ。

この例文集をカードを使って覚えようとして、すぐに挫折した。最大の敗因はカードにしたこと。繰り返し読んで結果として覚えてしまえばよかった。

それよりも、もっと大切なことを後年気がついた。文法を説明するための例文の暗記だ。

== 文法書の例文を暗記すること

英語の暗唱用例文には、会話、作文、単語、読解などそれぞれの用途に合わせて多くの参考書がある。高校生の頃、それらの例文集の違いについて理解できなかったし、そもそもなぜ文法の例文を覚える必要があるのか、全くもって理解できなかった。

文法の項目を覚えれば良いのに、なぜわざわざ例文を暗記するのだろうかと。

文法事項を十分理解した上で、その例文を覚えてしまえば、その文法をより自由に使いこなせるようになるからだ。そして、瞬時に思い出すことができる。

それは理解が先立たない、単なる例文暗記ではない。
例文とは、理解の手助けになる文のことだ。目的と手段の違いを残念ながらよく理解できていなかった。英会話の例文と取り扱い方の違いが分からなかったのだろう。

そして、先生に紹介していただいた読解用の例文集の前書きに「内容が分からないものを暗唱するのは無意味だ」とはっきり書いてある。なんども繰り返し目にしていたのに、ついに高校生の頃はその意味を理解しなかった。

現在、人気のある受験用文法書は600ページ超のものがほとんどだが、高校指定の文法の参考書は500ページ弱で、そのうち1/3が読解や作文の練習問題、さらに特殊構文や発音の章を除けば、実際の文法の説明は300ページ収まっている。全ての章にわたって例文を暗記することが十分可能な分量だ。そのためにこの参考書は選ばれたのだと思う。

高校入学直後に先生のすすめにしたがって、例文暗記をしてしまったら、以後どれだけ質の高い英語の勉強ができたかということを思うととても残念だ。

== 参考書の例文の覚えるなら

高一の頃の自分に例文集の使い方を教えるならこうなるだろう。基本的には例文だけを暗唱するのは勧めない。

紙に書き出したり、カードにするのは厳禁。アプリに入れるのもペースが遅くなるので勧めない。本を何度も通読するだけでいい。音読を録音して何度も聞き直すのがいい。自分の声の方が、記憶に残りやすいので付属音源がなくても心配ない。

=== 文法の例文

文法の参考書は、各章の内容を通読し、章末の例題を解く(ここまでは、自分も3周くらいやった) 。そのあとに例文を読み、それぞれの例文が示している文法のルースを思い出すことだ。何度も繰り返して例文を読み、文法項目を理解しているか確認するのが良い。

== 読解の例文

例文のカードを作ろうとして挫折したが、まず純粋に読解の参考書として使えば間違えない。

例文の説明を読み、英文和訳の練習問題を解く。その後、例文、練習問題、章末問題を繰り返し読み、各例文が取り上げている構文上の項目が理解できているか確認する。繰り返し読むのがいいだろう。

例文、練習問題、章末問題と文章の量が長くなっていく。問題となる例文がひとまとまりの文章の内容の中でどう機能しているか、前後にはどんな表現が現れやすいか注意する。

書き言葉なので黙読で繰り返し読んで、読むスピードの限界に挑戦する練習や、一見して理解できる英語の塊の幅を広げる練習もできる。

== 丸暗記を否定するわけではない

新しい言語を学ぶ時、基本的な会話フレーズや活用表は、さっさと丸暗記する方がいい。だんだん習熟度が高くなると、理解と組み合わせて覚えなければならない規則や表現が出てくる。文法の例文や、構文の例文の丸暗記が苦もなくできてしまうのなら、もちろんやってしまえば良い。挫折しなければ全然問題ない。

