---
slug: "6-auditory-learning-with-smartphone"
date: "2020-11-14T14:06:05+00:00"
lastmod: "2020-11-14T14:06:05+00:00"
title: "#6: スマホを使った録音学習はとても効率的でおすすめ"
type: "blog"
categories: ["録音学習"]
tags: ["音声学習","録音","スマホ"]
excerpt: "スマホを使った録音学習の利点と最初に注意すべき点についてまとめてみた"
---
= スマホを使った録音学習はとても効率的でおすすめ
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: スマホを使った録音学習の利点と最初に注意すべき点についてまとめてみた
:toc: macro
:toc-placement:
:toclevels: 1
:icons: font

{description}

toc::[]


== スマホを使った録音学習はこんなに素晴らしい

link:/blog/4-how-to-learn-vocabulary-book-for-exam/[以前書いた記事]の検証のために、1ヶ月間録音学習を続けたら、信じられないペースで学習が進んで驚いている。ただ本で学んだ内容で覚えておきたいことをスマホに録音し、あとで聴き直すだけだ。古文単語帳、大学受験英単語帳、英文読解例文集、高校文法書を仕上げることができた。また、オンライン英会話のデイリーニュース教材 の復習も録音学習に投入している。実際に使った時間は通勤時間と昼休みのおおよそ1日90分くらい。
そこで、忘れないうちに、録音学習を始めた時の注意点をまとめておこうと思う。

== 1. まず最初に注意すべきこと

録音学習をはじめて一番気になるのは、自分の声だ。強い抵抗感を感じる。しかしその抵抗感は、一週間もすれば慣れてしまう。そして自分の声の方が記憶に残りやすい。自分の声というのは録音学習における最大の武器だ。だから、最初は徐々に自分の声を聞くのに慣れていくつもりで聞いていこう。

== 2. 録音すべき項目どんどん洗練されていく

自分の声に慣れるにしたがって、気がつくのは、この教材録音学習に向いていないのではという疑念だ。例えば文字でノートを取るしても、何をノートに書くかは教材によって違う。音声でノートを取る場合も同じで、自分で繰り返し音声ノートを聞きなおすことで、何を録音すれば良いか、試行錯誤で洗練されていく。

だから、始めた頃の録音内容だけで、録音学習の良し悪しを早急に判断しないでほしい。

例えば古文単語を覚えるなら、語義の他に、例文を読むべきか、さらにその現代語が必要かなど、なにを録音すると一番記憶しやすいか分かってくるようになる。

== 3. 速度調節アプリを使って復習を高速化する

録音ノートの再生には耳コピ用のアプリlink:http://hayaemon.jp[ハヤえもん^]を使って大体1.5〜2.0倍速で聞いている。元は5分のデータでも速度を上げれば3分以内に済ませることができる。だから、どんどん録音データが溜まってもそれほど復習の時間確保に困らない。さらに早く聞くことで、理解の瞬発力が高まる。

== 4. 聞き流しは機能しない

録音ノートをよく聞こうと意識しないと復習としては効果がない。たとえ倍速であっても耳を傾けるから記憶に残り理解が深まる。聞き流しはやってはみたがうまくいかなかった。反対に速聴であっても精聴であれば機能する。

ただし、睡眠学習に効果があるかないかは、まだ試していないので今後の研究課題だ。

== 5. 野外でも学習できる

野外での録音学習はとてもおすすめだ。平日は昼休みに、休日は午後に公園に行って1時間弱録音学習をしている。そして、音声の吹き込みもしている。録音データに公園に住んでいる鳥の鳴き声とかが一緒に記録されている。その時のエピソードも一緒に記憶できるのでとても効率が良い。公園から戻りながらでも録音データを復習ができる。

== 今後の予定

あまりに高速で学べるので、今後は全ての教材を録音学習に振り切る予定だ。
すでに紙ベースで学んでいるポルトガル語基本語彙1600をスマホで復習する予定。他には英語のコロケーション例文集かコロケーション辞典を覚えようかと思っている。また小説暗記も録音学習でどれだけ効果があるか試してみようと思う。


