---
slug: "7-faq-slash-reading-for-classics"
date: "2020-11-15T08:42:00+00:00"
lastmod: "2020-11-15T08:42:00+00:00"
title: "#7: マダム式古文読解 FAQ"
type: "blog"
categories: ["オンラインコース"]
tags: ["動画","文語文法","古文読解","FAQ"]
excerpt: "マダム式古文読解シリーズの使い方に関するよくある質問とその答えを動画内の説明やコメント投稿を参考にまとめました。"
---
= マダム式古文読解 FAQ
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description:　マダム式古文読解シリーズの使い方に関するよくある質問とその答えを動画内の説明やコメント投稿を参考にまとめました。
:toc: macro
:toc-placement:
:toclevels: 1
:icons: font

{description}

toc::[]



== マダム式古文読解について

マダム式古文読解とは、link:https://www.youtube.com/channel/UCwjyutqnErtOfOFYUZa7USg/featured?pbjreload=102[マダム百合子先生]作成の古文読解のYouTube動画です。基本読解12回、実践編 文学史1回、実践編 説話読解20回からなります。スラッシュリーディングをしながら、大学受験の古文の読み方、その時の頭の働かせ方を丁寧に説明する内容となっています。

基礎講座12回分の一覧はlink:/blog/slash-reading-for-classics/[過去の投稿]でまとめています。


== どんな古文単語帳を選べば良いですか

覚えるべき単語量は、重要単語(指示語を含む) 300 + 熟語・慣用句 70 + 呼応表現 20 + 敬語 30 = 410〜430位です。

市販の単語帳の中でのオススメは、桐原書店のlink:https://www.amazon.co.jp/dp/4342350742[読んで見て覚える重要古文単語315^]です。ただし、実際に書店で手にとって自分に合うかどうか確認してください。

参考: {{< ytm-link EEGFYROH9XM 1363 >}}第8回　重要単語を覚える前にこれだけは知っておいてほしいこと{{< /ytm-link >}}

== 辞書は必要ですか

不要です。英語とは違い重要単語をきちんと頭に入れておく方が大切です。上級者のみ使用可です。

参考: {{< ytm-link EEGFYROH9XM 755 >}}第8回　重要単語を覚える前にこれだけは知っておいてほしいこと{{< /ytm-link >}}

== 古文の復習方法を教えてください

予備校や塾に通っている場合はその教材を、独学の場合は解説の多い問題集でなく、できるだけたくさんの文を扱った問題集を使って、その文章の中の助動詞と敬語が完璧に自力で抜き出せる・判断できるところまで、まず持って行きます。

マダム式読解法を取り入れる場合は、スラッシュを正しい位置に入れ、その上で（心内文）を付けることと「ぞ・なむ・や・か・こそ」がその文でどのような働きをしているのか考えながら読む訓練をします。主語はどういう理由でその人になったのか、なぜその人ではいけなかったのか人に説明できるまで理解します。

一番やってはいけないのは、二度と出会うことないその文章にこだわって内容を細かく追及すること。

次にやる文章を読み解くために必要な『知識のストック』が最も大切であることを理解してください。

参考: link:https://www.youtube.com/watch?v=y0CE1PoTr68[第9回　敬語なんてチョロい！種類と意味を一日でコンプリート　内コメント^]

== マダム式古文読解が終わったらどんな問題集を使えば良いですか

河合出版やZ会から出ているもので、題数が多く、いろんな出典を扱っている問題集、あるいは学校の教科書や過去に受けた模試の問題などです。

予備校の先生の参考書は、それぞれの個性が強すぎ、マダム式スラッシュリーディングと併用すると混乱してしまうと思うからです。

参考: link:https://www.youtube.com/watch?v=2VaZQsB8MnY[マダム式古文part２㉑　実践編　「十訓抄・武正といふ舎人のかなしう」内コメント^]

== どれくらいの読解練習をすれば良いですか

一年間で50題。「物語」「日記」「説話」「随筆」「歴史物語」「軍記物語」「歌論」の各ジャンルを最低一つずつ解くことが必要です。


参考: {{< ytm-link At95CRmsEdA 50 >}}第11回　あなたの主語がとれない原因はこれです！{{< /ytm-link >}}

参考: {{< ytm-link i4AiSBr-4HM 30 >}}マダム式古文part２➀　実践編　文学史と竹取物語{{< /ytm-link >}}

{{< ytmodal-script >}}

