---
slug: "8-how-to-revamp-math-proficiency"
date: "2021-09-26T10:09:48+00:00"
lastmod: "2021-09-26T10:09:48+00:00"
title: "#8: 数学が苦手ではないのに、成績に結びつかなかった高校生の頃"
type: "blog"
categories: ["セルフ受験・受験DIY"]
tags: ["数学","独学"]
excerpt: "数学が苦手ではないのに、成績に結びつかない状況を解決する大切なことと、その解決方法がわかったので、自分のために記録に残します。"
---
= 数学が苦手ではないのに、成績に結びつかなかった高校生の頃
:author: luminousspice
:lang: ja-jp
:encoding: UTF-8
:keywords:
:description: 数学が苦手ではないのに、成績に結びつかない状況を解決する大切なことと、その解決方法がわかったので、自分のために記録に残します。
:toc: macro
:toc-placement:
:toclevels: 1
:icons: font

{description}

toc::[]

== 好きな教科の成績が良くない不思議の原因がやっと分かった

業務上、場合の数、確率、数列漸化式をよく使う。現状でも特に業務に支障ははないのだが、そのような問題を瞬殺できるようになったら良いと思い、学び直して見た。

その中で、高校生の時に数学の勉強と成績が直結しなかった理由が分かった。それは実は至極明快なことであったが、その当時はまったく気が回らなかった。だから、自分のために忘れないように記録しようと思う。

高校の時の数学をどのように学んだかというと、授業で教科書の例題の解説をし、並行して問題集を自習後、定期テスト、別の復習用問題集を次の定期テストまでの課題になった。高2の10月ごろ数学1A2Bまで終わり、高3の夏休み前後に数3が終わる進度の公立高校で学んだ。その当時は教科書の説明や例題は自力で理解でき、練習問題は解けるが、節末、章末問題レベルになると分からない問題が出てくる状態だった。

高1最初の定期テストで思うような成績が残せず、その後挽回しようとして、次の単元で頑張って問題を解いたが結局思うような成績を残せなかった。これは数学だけに起こった現象で、その理由がずっとわからなかった。


=== 躓きの元はこれだ

確率と数列の解き直しをして気がついたことは、高校の数学は最初に学ぶ式の計算に関する単元が、全ての単元の基礎になっていて繰り返し出てくることだ。

数学Iの数と式、二次関数、数学IIの複素数と方程式・式と証明が現行の科目の単元にあたる。

ベクトル、数列、微積分などの新しい単元で新しい考え方を学んで、公式や定理に具体的な条件を当てはめるだけの練習問題は解けても、すでに学んだ単元と組み合わせた問題が出る節末、章末問題に苦戦することになる。

また、この単元の章末問題や教科書傍用問題集の同じレベルの問題に、計算や証明のためのコツを学ぶ問題が含まれている。このコツは、後の単元で説明もなく繰り返し問題に出てくる。説明を読んで唐突に出てくる飛躍はこれが原因だった。

分からないことを調べようとして教科書を繰り返し読んでいても、定理や公式の導出、例題には目がいくが、章末問題の問題文までは目が届かなかったので気づけなかった。

つまり、高校数学の最初に学ぶ式の計算の単元の理解不足、その科目で学ぶ計算や証明の工夫も身についていなかった。

この単元は、入学前の春休みの課題になっていて、中学で学んだことと大差ないので侮っていたこと、高校の定期テストで求められるレベルがよくわかっていなかったことが良い成績が取れなかった原因だろう。

これはスランプではない。だから、放っておいても自然に回復しない。ただ理解の足りない知識は復習すれば良い。ただ、新たに学ぶのではないので、早く対応できる。

== 2週間でできる改善策

まず理解しておきたいのは上達には、自分の実力プラス1の練習を繰り返すことが最も効果的だということ。数学の問題で実力プラス1とは、自分が何も見ずに使いこなせる知識に、たった１つの知識、つまり数式、公式、あるいは式の解釈を加えることで解けるようになる問題のことだ。

このレベルの問題を一問ずつ解いて、解けなかった問題から必要な知識を一つづつ拾い集めることが、最も効果的な解決策だ。東欧のことわざの「ゆっくり歩けばと遠くまで行ける」というつもりで焦らずに取り組めば良い。

自分のことを振り返ってみると、教科書の節末、章末問題につまずいていたので、このレベルの問題が一番適している。同じレベルの追加問題としては、学校で配布した復習用の問題集、シニア数学演習1A2B受験編が一番適している。分量にして14項目、約120題ほどになる。A問題とB問題は両方解いたほうがいい。問題の難しさと解ける解けないは別問題で、B問題の方が正解率が高い場合もあるからだ。

毎日見開きの10問を解いていけば、二週間で終わる。なお、10問の中に問題文を読んだだけで、解法や答えが思い浮かぶ問題は飛ばして良い。仕事をしながら自分で実際に同じペースで解いて見て無理なく終えることができたので、高校生の日常学習に組み込んでも無理なく終えることができると思う。

シニア数学演習は数研出版の問題集に特徴的な簡潔なヒントや略解は自分に必要なことだけを書いてくれるので、時間を節約できてとても使いやすい。

=== 教科書傍用問題集を使いたいと思うけど

高校生の頃、教科書傍用問題集をひたすら解いていたので、こちらを最初に思い浮かべるかもしれないが、問題の難易度の幅と配列順からシニア数学演習を勧める。また、シニア数学演習の方が学校の授業の進度と近く、既習の問題は解いた記憶が鮮明で素早く復習しやすく、未習の問題は定期テスト対策になるので成績に直結する。

シニア数学演習は問題の難易度が揃っていて、さらに難易度順に問題を配列しているので、復習用には傍用問題集よりも使いやすい。傍用問題集教科書の節末、章末レベルの「重要問題」の難易度の幅が大きく、解き難い。教科書の例題の直後にある問レベルの問題から大学入試問題の標準レベルの問題まで、一冊の中に幅広い難易度の問題を収録していて、目移りしやすく、今の目的には使い難い。

=== シニア問題演習以外の選択肢

もし同じことをしたい人がいて、学校で復習用に学習参考書を使っている場合は、教科書の節末、章末問題レベルの問題が代用できる。参考書の先頭にある説明を調べると、どの問題を使うべきかわかる。

教科書とシニア数学演習を間をつなぐ説明がもう一声欲しい、学校指定の学習参考書の説明の仕方が合わない場合は、実教出版の10日間あればいい! 短期集中ゼミ数学IAIIBを勧める。
 短期集中ゼミ数学IAIIBでは対象分野は34題ほどだ。例題の中のアドバイスという項目が端的で大変わかりやすい。この34問を解き終えたら、シニア数学演習に戻ると結構楽に解けるようになると思う。

== その後やってほしいこと

シニア数学演習が終わったら、教科書に載っている複数の章にまたがる発展問題、演習問題も解いておいて欲しい。そして、授業の進度に合わせて、引き続きシニア数学演習も解き続けて、なるべく早い時期に全問解き終えておくと、次のステップに入りやすくなる。

== まとめ

高校数学は、新規の単元を既知の知識と結びつけて理解することを繰り返すことが大切で、その土台となる単元を最初に配置している。だからこの単元の完成度が全ての単元の成績に直結する。

「上達に効く実力プラス1の練習」と「ゆっくり歩けば遠くまで行ける」が必要な数学の実力を回復する考え方だ。

この後で、大学受験を自力で準備するのための、数学教科書傍用問題集の使い方、教科書の理解、長時間問題を考えること、先取り学習について書いていこうと思う。